### ISSUE TITLE
Assistance to Optimize Application Performance on Current VM

### ISSUE THREAD

**Issue by ideas-duck** [blkchain/blkchain#17]
Hi, Firstly, I want to express my gratitude for the **incredible project** you've developed. It's truly impressive. 
However, I've encountered an issue while running the application and could use some assistance in optimizing its performance on my local machine.

Here are the details of my setup:

> Windows host machine (11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz   2.50 GHz)
> Virtual Ubuntu VM running on an SSD drive
> Full Bitcoin node on the same SSD drive
> Second SSD drive added to the same VM for storing Postgres data
> SSD read/write speeds from with the VM: Timing O_DIRECT disk reads: 642 MB in 3.03 seconds = 212.12 MB/sec

VM specifications:
> 25GB RAM
> 4 CPUs assigned

The application 'import' is running on the same VM that has the bitcoin Node, and postgres is installed on the same VM.

I've used the following command to start the application:
`./import -connstr "host=192.168.X.X dbname=blocks sslmode=disable" -cache-size 100000000 -blocks ~/.bitcoin/blocks
`
I've assigned the highest priority to the import application using the 'nice' command, but the performance is not close to what's indicated in the ReadMe.md.

Output example:
`2024/01/10 22:04:23 Height: 226584 Txs: 14588217 Time: 2013-03-18 18:57:27 +0200 SAST Tx/s: 626.154314 KB/s: 272.560214 Runtime: 6h28m18s`
_based on the current output, it seems my VM is not running the application optimally._

Top Command shows `53.3-60% CPU usage, and I've updated the Postgres config with recommended values for fast import.`

I would **greatly appreciate any advice or assistance on how to enhance the processing speed and align it with the expected output in the ReadMe.md.**

Thank you for your time
#AwesomeProject

**Comment by grisha** [comment]
If I understood you correctly, you're running the `import` process in a VM (Ubuntu) inside a Windows machine. 

Is PostgreSQL db running on the same machine? If so, i.e. _both_ import and postgres are on the same instance, then your performance is probably about right. 

In the README import and postgres are running on two separate hardware servers. Note that the import process appears to be more demanding on the "client", i.e. the machine running the `import` command.

**Comment by ideas-duck** [comment]
> If I understood you correctly, you're running the `import` process in a VM (Ubuntu) inside a Windows machine.
> 
> Is PostgreSQL db running on the same machine? If so, i.e. _both_ import and postgres are on the same instance, then your performance is probably about right.
> 
> In the README import and postgres are running on two separate hardware servers. Note that the import process appears to be more demanding on the "client", i.e. the machine running the `import` command.

Hi grisha, **thanks** for the prompt response :)
Yes i currently have the database and the application running on the same Virtual Machine.

**I will run the application & DB on 2 different machines and give further feedback.**

Kind Regards
