### ISSUE TITLE
Where is github.com/blkchain/blkchain/btcnode?

### ISSUE THREAD

**Issue by abrkn** [blkchain/blkchain#5]
https://github.com/blkchain/blkchain/blob/master/cmd/import/import.go#L14

**Comment by grisha** [comment]
I think it's fixed now, try again?

**Comment by abrkn** [comment]
I got impatient and made my own explorer: http://drivenet.explore.drivechain.ai

It's pretty neat. Supports GraphQL and both client/server side rendering. https://github.com/abrkn/dcex

**Comment by grisha** [comment]
Neat! I was hacking on a block explorer too, mine still needs a couple days of work, and it's mostly Go (with React on the UI end). I'm a little rusty on server-side JS to understand how dcex works - does it fetch block data via RPC and then store it in Postgres? BTW - looking at the PG schema - you need to make sure that same transaction can appear in more than one block (in case of a split, and then there is `e3bf3d07d4b0375638d5f1db5255fe07ba2c4cb067cd81b84ee974b6585fb468`), I learned that the hard way. :)

**Comment by abrkn** [comment]
Yes, I am using RPC to avoid having to parse blocks. The main reason for this is that I want compatibility with various forks that may not use the exact same file format.

As for a tx appearing in multiple blocks, I started off not having `block_hash` in the `tx` to support forks, but decided I was aiming a little high for the first version. My plan is to only store the primary chain in the database for now, but then move to re-add `tx_block` table and marking each `block` with a field indicating whether it's attached to the chain tip.

It's pretty cool to be able to see orphaned blocks and even double spends in the explorer. Maybe even useful for diagnosis.

I plan to do as much as possible in Postgres to take advangage of ACID, using triggers to update stats when reorgs occur.
