### ISSUE TITLE
Block chase after initialization is complete

### ISSUE THREAD

**Issue by xiaoqge** [blkchain/blkchain#8]
@grisha   I did not specify the nodeaddr and wait options during the first start of the import. After the initial import is completed, can I catch up?

**Comment by grisha** [comment]
Yes - you can just keep it running with -nodeaddr pointed at a full node (i.e. core) and -wait and whenever a new block appears it will get added.

**Comment by xiaoqge** [comment]
Thank you for your reply, but I did not specify the wait parameter after the import was completed at the first start, so after the import is completed, the restart will prompt that the table already exists

```
	if err := createTables(db); err != nil {
		if strings.Contains(err.Error(), "already exists") {
			// this is fine, cancel deferred index/constraint creation
			firstImport = false
			log.Printf("Tables already exist, catching up.")
		} else {
			return nil, err
		}
	}
```

**Comment by xiaoqge** [comment]
Thank you very much for your reply, but if I execute the following command, it will time out. I make sure that my rpc can connect normally.
```
root@bitcoind:/opt/bitcoin_etl/blkchain-master# ./import -connstr "host=127.0.0.1 user=postgres password=data dbname=bitcoinblocks sslmode=disable" -nodeaddr 10.10.0.3:8932 -nodetmout 100 -wait
2021/05/16 22:30:03 Reading block headers from Node (10.10.0.3:8932)...
2021/05/16 22:30:05 Warming up the txid cache going back 6 blocks...
2021/05/16 22:30:08 Warming up the cache done.
2021/05/16 22:31:43 Error catching up from btc node: Connection timeout
```

**Comment by xiaoqge** [comment]
> Yes - you can just keep it running with -nodeaddr pointed at a full node (i.e. core) and -wait and whenever a new block appears it will get added.

Hello, are you still there? This problem has troubled me for several days, I hope to get your help, thank you very much

**Comment by grisha** [comment]
The command I use for catching up is:
```
./import -connstr "host=X.X.X.X dbname=<dbname> sslmode=disable" \
   -cache-size 32949120 -nodeaddr X.X.X.X:8333 -wait
```

You don't need RPC for this, this is just over normal bitcoin core protocol on port 8333. The above command can be left running forever and it will just append new blocks as they appear.
